# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 00:18
from __future__ import unicode_literals

from django.db import migrations, models
import django_thumbs.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piece_type', models.CharField(blank=True, max_length=100, null=True)),
                ('image', django_thumbs.db.models.ImageWithThumbsField(upload_to='images')),
                ('frontpage', models.NullBooleanField(default=False)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('level', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
            ],
        ),
    ]
