# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 01:16
from __future__ import unicode_literals

from django.db import migrations, models
import django_thumbs.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('image', django_thumbs.db.models.ImageWithThumbsField(blank=True, null=True, upload_to='images/skill')),
                ('level', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='piece',
            name='software',
            field=models.ManyToManyField(related_name='software', to='mainapp.Software'),
        ),
        migrations.AddField(
            model_name='software',
            name='image',
            field=django_thumbs.db.models.ImageWithThumbsField(blank=True, null=True, upload_to='images/software'),
        ),
    ]
