# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 01:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20160128_0116'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='piece',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
